name: vmango-lab-demo
channels:
  - fredboudon
  - conda-forge
dependencies:
  - openalea.lpy=3.8.0
  - openalea.plantgl=3.9.3
  - xarray-simlab=0.5.0
  - jupyterlab>=3.0.*
  - jupyterlab_widgets
  - ipython=7
  - toml
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pycairo
  - pip
  - pip:
    - pgljupyter==1.1.0
    - python-igraph==0.9.6
    - git+https://github.com/jvail/vmango-lab.git
