channels:
  - fredboudon
  - conda-forge
dependencies:
  - alinea.caribu
  - openalea.lpy=3.8.*
  - openalea.plantgl=3.9.*
  - xarray-simlab=0.5.*
  - jupyterlab>=3.0.16
  - jupyterlab_widgets
  - ipython=7
  - toml
  - matplotlib
  - numpy=1.20.*
  - pandas
  - sparse
  - scipy
  - pycairo
  - pip
  - pip:
    - pgljupyter==1.1.0
    - python-igraph==0.9.6
    - git+https://github.com/jvail/vmango-lab.git@v1.0.0
