name: Testing notebook using Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      #max-parallel: 5
      matrix:
        # os: [ "macos-latest", "ubuntu-latest", "windows-latest"]
        os: [ "ubuntu-latest"]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: fredboudon,conda-forge
        environment-file: environment.yml
        activate-environment: vmango-lab-demo

    - name: Setup conda
      run: |
        # Setup conda
        sudo conda activate vmango-lab-demo
        sudo conda install pytest
        pip install nbmake

    - name: Test notebooks 
      run: |
        cd notebooks
        sudo conda activate vmango-lab-demo
        pytest --nbmake

